# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\import_dictionary.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.description = QtWidgets.QLabel(Dialog)
        self.description.setTextFormat(QtCore.Qt.RichText)
        self.description.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.description.setObjectName("description")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.description)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.chooseFileButton = QtWidgets.QPushButton(Dialog)
        self.chooseFileButton.setObjectName("chooseFileButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.chooseFileButton)
        self.filenameLabel = QtWidgets.QLabel(Dialog)
        self.filenameLabel.setText("")
        self.filenameLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.filenameLabel.setObjectName("filenameLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.filenameLabel)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dictionaryNameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.dictionaryNameLineEdit.setObjectName("dictionaryNameLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.dictionaryNameLineEdit)
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setObjectName("addButton")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.addButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.description.setText(_translate("Dialog", "Description"))
        self.label.setText(_translate("Dialog", "Dictionary file"))
        self.chooseFileButton.setText(_translate("Dialog", "Choose file"))
        self.label_2.setText(_translate("Dialog", "Dictionary name"))
        self.addButton.setText(_translate("Dialog", "Add"))
